FROM golang:1.22.0-alpine3.19

WORKDIR /app

COPY .. .

RUN apk add gcc musl-dev
RUN go mod download

RUN go install github.com/githubnemo/CompileDaemon@latest

ENTRYPOINT CompileDaemon -exclude-dir=.git -exclude-dir=docs --build="go build cmd/pdfy/main.go" --command="./main"